services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    tty: true

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./db/.env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=transcription_db
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=django_password
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/app
      - front_node_modules:/app/node_modules
    command:
      - "sh"
      - "-c"
      - "npm install && npm start --port 3000"
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
  front_node_modules:
